### ISSUE TITLE
Publish plugin to maven central

### ISSUE THREAD

**Issue by a1dutch** [enear/keepachangelog-maven-plugin#5]
Would it be possible to publish the plugin to maven central?

You can following the steps [here](http://central.sonatype.org/pages/ossrh-guide.html).

**Comment by unit73e** [comment]
Yeah not a problem. I'll publish the plugin in a few days. Sorry for taking a while to answer.

**Comment by unit73e** [comment]
Done. This release thing was much harder than I thought. It's not in central search but it's in central. This project was kind of getting dust and I have a lot of fixes to do but at least it works.

https://repo1.maven.org/maven2/co/enear/maven/plugins/

**Comment by a1dutch** [comment]
Cool thanks, will give it a spin. The search can take a while to get updated.
