### ISSUE TITLE
Add SSH support to access SCM

### ISSUE THREAD

**Issue by galegofer** [enear/keepachangelog-maven-plugin#7]
Hi there,

First at all, thanks for the plugin!.

Second, not exactly a bug but a feature, will be feasible to implement ssh connection also when accessing to the SCM?.

Cheers

**Comment by unit73e** [comment]
Hello

I don't see why it shouldn't be possible. I'll add that feature in the next release. I'm just not sure when given we're near Christmas and new year.

**Comment by unit73e** [comment]
Hello @galegofer 

~I finally had spare time to check this request however I didn't find any problem with an SSH URL. What problem did you have? Maybe I can help.~

Never mind. My SCM connection wasn't properly changed. Confirmed that it does not work with a GIT URL. It doesn't seem very hard to fix so I'll probably have this feature today.

**Comment by unit73e** [comment]
I checked the code in more detail and it seems I made some poor decisions at the time. To sum up the `connectionUrl` and `repositoryUrl` should probably be separate. One gets you the git origin URL but the repository web page can be different. The SCM entry in `pom.xml` does seem to be prepared for that but I'll have to think of a way for the URL to be something manageable. In any case you won't have to wait much longer. I'll try to have this fixed ASAP.

**Comment by unit73e** [comment]
Fixed. However as you'll notice I added another option I called `repositoryURL`. The issue is that the `connectionURL` (what Maven calls the Git URL) does not have to be the same as the web page URL, so I split those two. Check if this works for you.

**Comment by galegofer** [comment]
Nice, Thanks!, as soon as version 2.0.0 will be available at mvnrepository I will download and test it.
Thanks again!
